# Generated by Django 3.1.1 on 2021-03-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Рецепты', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
